### ISSUE TITLE
Accept and parse address string

### ISSUE THREAD

**Issue by chrisjaure** [mikeputnam/appletonapi#13]
It would be totally awesome if you could accept and parse an address string rather than expecting house number and street name in a very specific format.

I was using a javascript port of http://search.cpan.org/~timb/Geo-StreetAddress-US-1.04/US.pm that was working pretty well except it took 1.5s just to parse and execute the library! Really slowed down the app's load time.

Also would be nice if you could automatically convert street names like 18th to Eighteenth.

Thanks!

**Comment by mikeputnam** [comment]
I think I'll give [this library](https://github.com/pnpnpn/street-address) a try. The example seems exactly what we need to turn arbitrary addresses into the data points the upstream requires for search.

**Comment by chrisjaure** [comment]
Sounds good. I'm blocked until this is implemented because I have no fast, reliable way to parse the street address that I'm getting back from the google maps api for geolocation.

**Comment by mikeputnam** [comment]
Just for clarity, you need to be able to pass strings like the below to the API and get back a property key for the subsequent call. Right?

`addr = addr_parser.parse("1600 Pennsylvania Ave")`

**Comment by mikeputnam** [comment]
Will this work for you?  http://3-0.appletonapi.appspot.com/search?q=121%20Douglas%20St

Note the 3-0 version and simplified url parameter.

**Comment by chrisjaure** [comment]
Awesome, thanks @mikeputnam! Will try it out tomorrow, but that looks like it'll work.

**Comment by chrisjaure** [comment]
:+1: Works perfectly!

**Comment by chrisjaure** [comment]
Also addresses like `816 5th St` don't work because the ordinal needs to be spelled out, e.g. `816 Fifth St`. Do you think you can convert that?

**Comment by mikeputnam** [comment]
I've gotten the 5th => Fifth thing figured out, but the handling cardinal directions on the input will take some time.  I'll fork the [street-address parser](https://github.com/pnpnpn/street-address) I'm using and make the fix there. Maybe the upstream will accept the changes. (add N/North parsing separate from the base street name)

**Comment by chrisjaure** [comment]
Any update on the last issue? If not, I could probably add a hack to my client to strip out cardinals.

**Comment by mikeputnam** [comment]
Sorry nothing yet. I'll make that the next thing I work on.

**Comment by mikeputnam** [comment]
@chrisjaure Try out this separate deployment endpoint and let me know if it resolves this issue. If it does, I can then deploy it to the main API. Thanks!

http://test.appletonapi.appspot.com/

**Comment by chrisjaure** [comment]
@mikeputnam It's working pretty well except for one case. When using a full address like `100 Appleton St, Menasha, WI 54952, USA` (including the country) it fails with a 500 server error. Without the country, it works fine.

This is only an issue because the address I get back from google maps for the reverse geocode lookup includes the country.

**Comment by mikeputnam** [comment]
Added handling of 'USA'. Try again?

http://test.appletonapi.appspot.com/

**Comment by chrisjaure** [comment]
Works great. :+1:

Thanks for the fix @mikeputnam!
