### ISSUE TITLE
Add /crimes documentation to the README

### ISSUE THREAD

**Issue by mikeputnam** [mikeputnam/appletonapi#15]

**Comment by mikeputnam** [comment]
Hey @zgohr what do you think about the following idea for the /crimes route?

Since an open-ended call like start_date=2015-06-07 has a compound effect on data size and cpu quota due to all dates from that point forward being fetched, I propose we introduce some artificial rate limiting so that we do not exhaust the free tier of our daily Google App Engine quota.

Currently (2015-07-31) the above call results in ~6.18MB of data and ~17 seconds of cpu time. For context, the average of the other routes are in the neighborhood of ~1-2KB and 200-500 milliseconds.

What if... 

* We change the behavior of a "start_date" only call to only fetch that date.
* We change the behavior of no "start_date" or "end_date" to only fetch current date (or maybe no-op)
* We change the behavior of both "start_date" and "end_date" to only allow a maximum of 7 days. This would force clients wanting more than 1 week to make multiple calls. I'm thinking that legit clients wanting that much data would be relatively rare and this would ease up on the quotas by reducing the more common call to something like ~1MB and ~5 seconds.

**Comment by zgohr** [comment]
Sounds good!
