### ISSUE TITLE
Adhere to common API contract per https://github.com/mrosack/greenville-wi-api

### ISSUE THREAD

**Issue by mikeputnam** [mikeputnam/appletonapi#19]
In order to participate in and support mrosack/civic-hack-api-locator let's implement the same API.

This may require a backwards incompatible version change. We'll see.

**Comment by zo0o0ot** [comment]
I'm pretty flexible on getting input back for the pebble watch app, since there isn't a ton of code to change.  Just let me know if you'll keep the legacy API up if or when you introduce the breaking changes.

**Comment by mrosack** [comment]
I sent a pull request this morning - I don't think it requires removing the API calls that are already there, just adding a new one that implements the garbage/recycling contract.  Let me know your thoughts.

**Comment by mikeputnam** [comment]
Thanks @mrosack !  I'll give it a try this weekend.

**Comment by zo0o0ot** [comment]
If possible, could you give some info on what this means for the apps that use the API call?  It sounds like an additional call in addition to the existing ones.

**Comment by mrosack** [comment]
No problem -  the new flow would be:

- Ask the user for their zip code (54942 - greenville)
- Call http://civic-hack-api-locator.azurewebsites.net:80/api/implementations/byzipcode/54942 to get the listing of contract implementations for that zip code, which will return:

```json
[
  {
    "contractName": "upcoming-garbage-recycling-dates",
    "contractDescription": "Returns upcoming dates for garbage and recycling collection",
    "implementationName": "greenville-wi-garbage",
    "implementationApiUrl": "http://greenville-wi-api.azurewebsites.net/api/GarbageCollection"
  }
]
```

- Look for an item in that result with a contract name of "upcoming-garbage-recycling-dates", and if one exists you've got a client you can call!  You don't need to do this every time, once you know where the user lives you could cache that information and skip the api location step in the future.
- Call the implementationApiUrl, appending the correct parameters.  You would know the parameters from looking at the swagger documentation for the contract on the web interface to the civic hack locator (which doesn't exist yet).  Basically just pass through the address of the property in the addr query string parameter, for example: http://greenville-wi-api.azurewebsites.net:80/api/GarbageCollection?addr=W6683%20Spring%20Green%20Place%2C%20Greenville%20WI%2054942
- Use the results from that call to populate your interface!

I went ahead and added the AppletonAPI implementation of the contract for zipcodes 54911-54915 and 54919 as it was implemented in my pull request, just so you can get an idea of what it'd look like for appleton as well (obviously, it's not actually deployed to the AppletonAPI yet).  Let me know if you need any more info!
