### ISSUE TITLE
appletonapi.appspot.com looks like it was written by a non-designer; because it was!

### ISSUE THREAD

**Issue by mikeputnam** [mikeputnam/appletonapi#6]
As the working "production" endpoint, the placeholder page at http://appletonapi.appspot.com could be greatly refactored for beauty and information conveyance.

It should:

* Encourage participation both code and non-code!
* Be transparent about how the API works
* Include specific technical information to assist possible developers (Google App Engine docs, python docs, dependency notes.
* Encourage full usage of Github features for this project: wiki, issues, pull requests, assignees, lables, etc.
* Cite sources/upstream http://my.appleton.org/

**Comment by mikeputnam** [comment]
New idea! Instead of trying to maintain essentially duplicate info on the Github README and the API endpoint, let's just point to the Github README from the API side.

**Comment by zo0o0ot** [comment]
Smart thinking, dude,
